"""fixed_dish table created-1.

Revision ID: 0094d5952938
Revises: b38cacce3873
Create Date: 2025-03-30 11:06:56.809878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0094d5952938'
down_revision: Union[str, None] = 'b38cacce3873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_dish',
    sa.Column('fixed_dish_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sabji_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('roti_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('fixed_dish_id'),
    sa.UniqueConstraint('day_of_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_dish')
    # ### end Alembic commands ###
